name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # change as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # or add to requirements.txt
        pip install .
    - name: Run tests with pytest
      run: |
        cd unittest
        pytest